# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MARC-Lint
version:      1.4
version_from: lib/MARC/Lint.pm
installdirs:  site
requires:
    MARC::Record:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
